apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: golang-example-site
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/compute-full-forwarded-for: "true"
    nginx.ingress.kubernetes.io/use-forwarded-headers: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - site-golang.dev.a3v.me
      secretName: site-golang-dev-tls
  rules:
    - host: site-golang.dev.a3v.me
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: golang-example-site
                port:
                  number: 80
